services:
  server:
    build: ./cbc-docker-php7-nginx
    image: cbc-docker-php7-nginx
    container_name: cbs-some-container-name
    entrypoint: [ "bash", "-c", "sleep 5 && nginx && php-fpm7.4 -F"]
    volumes:
      - .:/usr/share/nginx/html
      - ./cbc-docker-php7-nginx/ssl:/etc/nginx/certs
      - ./cbc-docker-php7-nginx/nginx/site.conf:/etc/nginx/sites-enabled/default
    networks:
      default:
        ipv4_address: 10.2.0.30

networks:
  default:
    external: true
    name: cbc-docker-stack_vpcbr
